# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteuser',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
