# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_voteuser_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteuser',
            name='vote',
        ),
    ]
